apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrdevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
      - name: mrdevops
        image: aniket1805/firstpipelinejob
        imagePullPolicy: Always
        ports:
        - containerPort: 80
