apiVersion: v1
kind: Service
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080           # External service port
      targetPort: 80       # Container port
  selector:
    app: mrdevops
  type: NodePort           #
